---
# file: kubernetes.yml

- hosts: kubernetes
  become: true
  roles:
    - os
    - geerlingguy.ntp
    - docker
    - access

- hosts: kubernetes
  become: true
  tasks:
  - name: Fetch public keys
    fetch:
      flat: true
      src: /home/{{ cluster_user }}/.ssh/id_rsa.pub
      dest: /tmp/id_rsa_{{ inventory_hostname }}.pub

- hosts: kubernetes
  become: true
  tasks:
  - name: Add public keys to authorized_keys
    authorized_key:
      user: '{{ cluster_user }}'
      key: '{{ lookup("file", "/tmp/id_rsa_" + item + ".pub") }}'
    with_items: '{{ ansible_play_batch }}'

- hosts: kubernetes_admin
  become: true
  roles:
    - rke

- hosts: kubernetes_admin
  become_user: '{{ cluster_user }}'
  roles:
    - role: longhorn
      when: install_longhorn | bool
    - role: helm
      when: install_helm | bool
    - role: cert-manager
      when: install_cert_manager | bool
