---
- hosts: kubernetes
  become: true
  roles:
    - os
    - geerlingguy.ntp
    - docker
    - access

- hosts: kubernetes
  become: true
  become_user: '{{ cluster_user }}'
  roles:
    - rke-ansible
