---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: kubemaster-1
    box: ubuntu/focal64
    groups:
      - kubernetes_masters
      - kubernetes
    memory: 2048
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.56.11
  - name: kubenode-1
    box: ubuntu/focal64
    groups:
      - kubernetes_nodes
      - kubernetes
    memory: 2048
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.56.21
  - name: kubeadmin-1
    box: ubuntu/focal64
    groups:
      - kubernetes_admin
      - kubernetes
    memory: 1024
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.56.31
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  inventory:
    links:
      group_vars: ../../inventories/test/group_vars
  lint:
    name: ansible-lint
  config_options:
    defaults:
      pipelining: True
verifier:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
