---
# file: roles/docker/tasks/main.yml

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - software-properties-common
      - gnupg-agent
    state: present

- name: Docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Docker repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present
    filename: docker

- name: Pin the Docker version
  template:
    src: docker-ce-pin.j2
    dest: /etc/apt/preferences.d/docker-ce

- name: Install Docker
  apt:
    name: docker-ce={{ docker_ce_package }}
    force: yes

- name: Add cluster user to docker group
  user:
    name: '{{ cluster_user }}'
    groups: docker
    append: yes
